name: enhanced_coord
channels:
  - pyconll
  - defaults
dependencies:
  - python=3.7.5
  - pytorch=1.3.1
  - pyconll=2.2.1
  - pip=19.3.1
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - pip:
    - transformers==2.3.0

